version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:5.0.7-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command:
      - start_jobs.sh
    volumes:
      - '.:/onebitsanta'
    volumes_from:
      - box

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/onebitsanta'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box: